// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhdwoajmwpmzopbzshsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZHdvYWptd3Btem9wYnpzaHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDI0ODgsImV4cCI6MjA3NDU3ODQ4OH0.7kVGYQpLyhKHGg9uSNsTQgO2D236iuaoeDRkUs1nIrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});